version: "3.9"
services:
  monolith:
    image: monolithic-app
  haproxy:
    image: my-haproxy
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy:ro"

networks:
  default:
    driver: bridge