version: "3.9"
services:
  monolith:
    image: jh7939/monolithic:monolithic-app
  haproxy:
    image: jh7939/monolithic:my-haproxy
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy:ro"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

networks:
  default:
    driver: bridge