version: "3.9"
services:
  users:
    image: jh7939/microservices:users_microservice
  threads:
    image: jh7939/microservices:threads_microservice
  posts:
    image: jh7939/microservices:posts_microservice
  comments:
    image: jh7939/microservices:comments_microservice
  haproxy:
    image: my-haproxy
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy:ro"

networks:
  default:
    driver: bridge