version: "3.9"
services:
  users:
    image: jh7939/microservices:users_microservice
    pull_policy: always
    healthcheck:
      test: curl --fail http://localhost/api/users || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "3100"
  threads:
    image: jh7939/microservices:threads_microservice
    pull_policy: always
    healthcheck:
      test: curl --fail http://localhost/api/threads || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "3101"
  posts:
    image: jh7939/microservices:posts_microservice
    pull_policy: always
    healthcheck:
      test: curl --fail http://localhost/api/posts || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "3102"
  comments:
    image: jh7939/microservices:comments_microservice
    pull_policy: always
    healthcheck:
      test: curl --fail http://localhost/api/comments || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "3103"
  haproxy:
    image: jh7939/microservices:haproxy
    pull_policy: always
    ports:
      - "80:80"
      - "8404:8404"
      - "5555:5555"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy:rw"
  consul:
    image: my-consul
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
  registrator:
    command: "consul://localhost:8500"
    image: gliderlabs/registrator:latest
    container_name: registrator
    network_mode: host
    links:
      - "consul"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
networks:
  default:
    driver: bridge